
name: build android

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build and Publish APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-actions
          path: app/build/outputs/apk/debug/app-actions.apk
