# when continuous integration

name: Android Build

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    name: Build and Publish APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Use 'adopt' distribution for OpenJDK

      - name: Build with Gradle
        run: |
            chmod +x gradlew
            ./gradlew assembleDebug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

